version: "3.9"

services:
  app:
    container_name: server
    image: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "80:80"
